In [1]:
import pandas as pd 
import numpy as np

# Data Gathering

In [57]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [58]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [59]:
movies.shape

(4803, 20)

In [60]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [61]:
movies = movies.merge(credits,on='title')

In [62]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [63]:
movies.shape

(4809, 23)

In [64]:
## Remove unecessary Feature 
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

In [65]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [66]:
movies=movies[['movie_id','overview','title','genres','keywords','cast','crew']]
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [67]:
movies.isna().sum()

movie_id    0
overview    3
title       0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [68]:
movies.dropna(inplace=True)

In [69]:
movies.duplicated().sum()

0

In [70]:
import ast

In [71]:
def converted (text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [72]:
movies['genres']=movies['genres'].apply(converted)

In [73]:
movies['keywords']=movies['keywords'].apply(converted)

In [74]:
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"John Carter is a war-weary, former military ca...",John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [75]:
def con(text):
    l=[]
    c=0
    for i in ast.literal_eval(text):
        if c<3:
            l.append(i['name'])
        c+=1
    return l

In [76]:
movies['cast']=movies['cast'].apply(con)

In [77]:
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"John Carter is a war-weary, former military ca...",John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [78]:
def director(text):
    l=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director':
            l.append(i['name'])
    return l

In [79]:
movies['crew']=movies['crew'].apply(director)
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"John Carter is a war-weary, former military ca...",John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [80]:
def space(text):
    l=[]
    for i in text:
        l.append(i.replace(' ',''))
    return l

In [81]:
movies['cast']=movies['cast'].apply(space)
movies['genres']=movies['genres'].apply(space)
movies['crew']=movies['crew'].apply(space)
movies['keywords']=movies['keywords'].apply(space)
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,A cryptic message from Bondâ€™s past sends him o...,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,"John Carter is a war-weary, former military ca...",John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [82]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [83]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['cast']

In [84]:
movies.head()

,movie_id,overview,title,genres,keywords,cast,crew,tags
0,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [85]:
new=movies.drop(['genres','overview','keywords','cast','crew'],axis=1)

In [86]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [87]:
new['tags']=new['tags'].apply(lambda x:' '.join(x))

In [88]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words='english')

In [92]:
vector = cv.fit_transform(new['tags']).toarray()

In [93]:
vector.shape

(4806, 5000)

In [94]:
from sklearn.metrics.pairwise import cosine_similarity

In [95]:
similarity = cosine_similarity(vector)

In [96]:
similarity

array([[1.        , 0.07071068, 0.04901431, ..., 0.02247333, 0.0238705 ,
        0.        ],
       [0.07071068, 1.        , 0.05198752, ..., 0.02383656, 0.        ,
        0.        ],
       [0.04901431, 0.05198752, 1.        , ..., 0.02478408, 0.        ,
        0.        ],
       ...,
       [0.02247333, 0.02383656, 0.02478408, ..., 1.        , 0.07242068,
        0.04545455],
       [0.0238705 , 0.        , 0.        , ..., 0.07242068, 1.        ,
        0.04828045],
       [0.        , 0.        , 0.        , ..., 0.04545455, 0.04828045,
        1.        ]])

In [97]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [98]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [99]:
recommend('Gandhi')

The Wind That Shakes the Barley
A Passage to India
Ramanujan
Guiana 1838
Bloody Sunday

In [101]:
recommend('Spectre')

Quantum of Solace
Skyfall
Never Say Never Again
Casino Royale
From Russia with Love

In [102]:
recommend('Avatar')

The Book of Life
Star Trek Into Darkness
Aliens
Alien
Aliens vs Predator: Requiem

In [104]:
recommend("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
The Imaginarium of Doctor Parnassus
The Three Musketeers

In [105]:
recommend('John Carter')

Battleship
Star Trek: Insurrection
Damnation Alley
Lone Survivor
Captain America: The First Avenger

In [114]:
new.head(20)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
5,559,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...
6,38757,Tangled,When the kingdom's most wanted-and most charmi...
7,99861,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...
8,767,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he..."
9,209112,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...
10,1452,Superman Returns,Superman returns to discover his 5-year absenc...
11,10764,Quantum of Solace,Quantum of Solace continues the adventures of ...
12,58,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...
13,57201,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...
14,49521,Man of Steel,A young boy learns that he has extraordinary p...
15,2454,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...
16,24428,The Avengers,When an unexpected enemy emerges and threatens...
17,1865,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...
18,41154,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...
19,122917,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...

In [112]:
recommend("El Mariachi")

I Am Sam
Tiny Furniture
Bella
And Then Came Love
Vertical Limit

In [113]:
recommend('El Mariachi')

I Am Sam
Tiny Furniture
Bella
And Then Came Love
Vertical Limit

In [115]:
recommend('Avengers: Age of Ultron')

The Avengers
Iron Man
Iron Man 3
Captain America: Civil War
Iron Man 2

In [116]:
recommend('The Lone Ranger')

The Wild Bunch
Torque
The Legend of the Lone Ranger
West Side Story
District B13

In [119]:
recommend('Tangled')

Aladdin
Toy Story 3
Frozen
The Princess and the Frog
The Smurfs

In [120]:
recommend('Harry Potter and the Half-Blood Prince')

Harry Potter and the Chamber of Secrets
Harry Potter and the Order of the Phoenix
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Goblet of Fire
Harry Potter and the Philosopher's Stone

In [122]:
recommend('Man of Steel')

Batman v Superman: Dawn of Justice
Ong Bak 2
Superman Returns
Superman II
The Cold Light of Day

In [123]:
recommend('The Hobbit: The Battle of the Five Armies')

The Hobbit: An Unexpected Journey
The Hobbit: The Desolation of Smaug
The Lord of the Rings: The Fellowship of the Ring
The Lord of the Rings: The Return of the King
The Lord of the Rings: The Two Towers

In [132]:
new[30:50]

,movie_id,title,tags
30,558,Spider-Man 2,Peter Parker is going through a major identity...
31,68721,Iron Man 3,When Tony Stark's world is torn apart by a for...
32,12155,Alice in Wonderland,"Alice, an unpretentious and individual 19-year..."
33,36668,X-Men: The Last Stand,"When a cure is found to treat mutations, lines..."
34,62211,Monsters University,A look at the relationship between Mike and Su...
35,8373,Transformers: Revenge of the Fallen,Sam Witwicky leaves the Autobots behind for a ...
36,91314,Transformers: Age of Extinction,"As humanity picks up the pieces, following the..."
37,68728,Oz: The Great and Powerful,"Oscar Diggs, a small-time circus illusionist a..."
38,102382,The Amazing Spider-Man 2,"For Peter Parker, life is busy. Between taking..."
39,20526,TRON: Legacy,"Sam Flynn, the tech-savvy and daring son of Ke..."
40,49013,Cars 2,Star race car Lightning McQueen and his pal Ma...
41,44912,Green Lantern,"For centuries, a small but powerful force of w..."
42,10193,Toy Story 3,"Woody, Buzz, and the rest of Andy's toys haven..."
43,534,Terminator Salvation,"All grown up in post-apocalyptic 2018, John Co..."
44,168259,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...
45,72190,World War Z,Life for former United Nations investigator Ge...
46,127585,X-Men: Days of Future Past,The ultimate X-Men ensemble fights a war for t...
47,54138,Star Trek Into Darkness,When the crew of the Enterprise is called back...
48,81005,Jack the Giant Slayer,The story of an ancient war that is reignited ...
49,64682,The Great Gatsby,An adaptation of F. Scott Fitzgerald's Long Is...

In [126]:
recommend('The Amazing Spider-Man')

The Amazing Spider-Man 2
Spider-Man 3
Spider-Man
Hook
Pan

In [127]:
recommend('Robin Hood')

Noah
An Ideal Husband
Indiana Jones and the Kingdom of the Crystal Skull
The Man with the Iron Fists
The Quick and the Dead

In [128]:
recommend('Titanic')

Captain Phillips
Romance & Cigarettes
In the Heart of the Sea
The Notebook
Ghost Ship

In [129]:
recommend('Battleship')

Independence Daysaster
John Carter
Krull
Titan A.E.
The 5th Wave

In [130]:
recommend('Skyfall')

Spectre
Quantum of Solace
Never Say Never Again
Dr. No
Octopussy

In [131]:
recommend('Jurassic World')

Jurassic Park
The Lost World: Jurassic Park
Guardians of the Galaxy
A Sound of Thunder
Journey to the Center of the Earth

In [133]:
recommend('Alice in Wonderland')

Alice Through the Looking Glass
Mirrormask
Charlie and the Chocolate Factory
Spirited Away
The Indian in the Cupboard

In [134]:
recommend('Furious 7')

A Man Apart
The Fast and the Furious
Meet the Deedles
Fast Five
The Scorpion King

In [135]:
recommend('TRON: Legacy')

2001: A Space Odyssey
Transformers
The Giver
Iron Man
Seventh Son

In [136]:
recommend('Monsters University')

Monsters, Inc.
Monster House
Khumba
The Jungle Book 2
Saint John of Las Vegas

In [117]:
import pickle

In [118]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))